#!/usr/bin/env bash
#Job name
#SBATCH -J saturation
# Asking for N nodes
#SBATCH -N 16
# Output results message
#SBATCH -o %j.out
# Output error message
#SBATCH -e %j.err

#SBATCH -p longq
module purge
module load slurm/14.03.0
module load mpich/ge/gcc/64/3.1.4

FOLDER=/home-ext/stanisic/platform-calibration

mpirun -np 16 $FOLDER/src/saturation/saturation